version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    networks:
      - mssql_network
    restart: always
    volumes:
      - sql_data:/var/opt/mssql

networks:
  mssql_network:
    driver: bridge

volumes:
  sql_data:
    driver: local